# Generated by Django 3.1 on 2021-08-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210826_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_pages',
            new_name='BookPages',
        ),
    ]
