# Generated by Django 3.1 on 2021-08-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0006_auto_20210802_1140'),
        ('core', '0003_auto_20210826_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='bookcollection',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('category_id', 'book_id')},
        ),
        migrations.AlterUniqueTogether(
            name='bookcollection',
            unique_together={('collection_id', 'book_id')},
        ),
    ]
