# Generated by Django 3.1 on 2021-08-27 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210827_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lips',
            new_name='Libs',
        ),
        migrations.AlterField(
            model_name='bookpages',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpages',
            unique_together={('page', 'book_id')},
        ),
    ]
