# Generated by Django 3.1 on 2021-08-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210827_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libs',
            name='page_num',
        ),
        migrations.AddField(
            model_name='libs',
            name='page_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.page'),
        ),
        migrations.AlterField(
            model_name='libs',
            name='book_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
    ]
