# Generated by Django 3.1 on 2021-08-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210828_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libs',
            name='book_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
        ),
        migrations.AlterField(
            model_name='libs',
            name='page_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.page'),
        ),
        migrations.AlterField(
            model_name='libs',
            name='state',
            field=models.CharField(blank=True, choices=[('read', 'Read'), ('finish', 'Finish')], default=None, max_length=10, null=True),
        ),
    ]
