# Generated by Django 3.1 on 2021-08-29 03:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20210829_0511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libs',
            unique_together={('book_id', 'user_id'), ('page_id', 'user_id')},
        ),
        migrations.RemoveField(
            model_name='libs',
            name='state',
        ),
    ]
