# Generated by Django 3.1 on 2021-08-30 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210830_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='rates',
            unique_together={('user_id', 'book_id')},
        ),
    ]
