# Generated by Django 3.1 on 2021-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_newcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='searchable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='show',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, related_name='book_tags', to='core.Tag'),
        ),
    ]
