# Generated by Django 3.1 on 2021-09-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210910_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='tags',
        ),
    ]
